import type { Goal } from "@/lib/goal-types";

const seedTimestamp = "2025-05-01T00:00:00.000Z";

export const seedGoals: Goal[] = [
  {
    id: "seed-goal-net-pnl-may-2025",
    title: "2025年5月净盈利目标",
    category: "performance",
    metric: "netPnl",
    direction: "atLeast",
    targetValue: 5000,
    unit: "currency",
    periodType: "monthly",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    status: "active",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "seed-goal-review-completion-may-2025",
    title: "复盘完成率达到 90%",
    category: "process",
    metric: "reviewCompletionRate",
    direction: "atLeast",
    targetValue: 90,
    unit: "percent",
    periodType: "monthly",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    status: "active",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "seed-goal-max-drawdown-may-2025",
    title: "最大回撤不超过 5%",
    category: "risk",
    metric: "maxDrawdownPercent",
    direction: "atMost",
    targetValue: 5,
    unit: "percent",
    periodType: "monthly",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    status: "active",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "seed-goal-weekly-trade-limit-2025-05-26",
    title: "每周交易不超过 20 笔",
    category: "behavior",
    metric: "totalTrades",
    direction: "atMost",
    targetValue: 20,
    unit: "trades",
    periodType: "weekly",
    startDate: "2025-05-26",
    endDate: "2025-06-01",
    status: "active",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "seed-goal-avg-r-may-2025",
    title: "平均 R 达到 +0.80R",
    category: "performance",
    metric: "avgR",
    direction: "atLeast",
    targetValue: 0.8,
    unit: "r",
    periodType: "monthly",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    status: "active",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
